apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name: backend
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: -------
        ports:
        - containerPort: 8000

