apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: frontend
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        image: 548570664128.dkr.ecr.us-east-1.amazonaws.com/capstone-frontend
        ports:
        - containerPort: 80
