alertmanager:
  enabled: true

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

grafana:
  enabled: false  # since we install it separately
